### PR TITLE
Helmet visibility fix

### PR DESCRIPTION
**Pull request by Alyst3r**
Using 4.3.4 DBC file as a source, I adjusted flags in HelmetGeosetVisData.dbc. Helmets should properly hide specific parts now (so for example DK starting cowl hiding hair for goblin).

(Side note, not really tested since I introduced some crash inducing bug in my current test build of AC that does not allow me to even log properly without crash, but I think it should work in most cases - but there may still be some flaws that need polishing.)

### CODE REVIEW

**Comment by Alyst3r** [comment]
Ok, actually tested in game with both DKs, seems like it really does work.
WoWScrnShot_121922_011036
WoWScrnShot_121922_011201

**Comment by heyitsbench** [comment]
Would you be able to test item 7997 on Goblin rogues with this PR please?

**Comment by heyitsbench** [comment]
Also, for future reference, [here is the diff between stock WotLK HelmetGeosetVisData and the changes suggested here](https://github.com/heyitsbench/pubrepo/commit/dc3f2bb7089ccba553436fc2c6825ac98201d5be).

**Comment by Alyst3r** [comment]
Well, it did take longer than expected since I just re-downloaded and recompiled everything from scratch since still didn't find what I did break in my work folder.
Good news is I've found out correct flag, for ID 369 flag 61150 should be changed to 60638.
test222
And for future reference, it did take a while to make any sense from values in this file but turns out it's just a normal race bitmask, just left shifted by 1 (it actually is staded on wowdev.wiki but I skimmed through article and didn't realise until later).

**Comment by heyitsbench** [comment]
> And for future reference, it did take a while to make any sense from values in this file but turns out it's just a normal race bitmask, just left shifted by 1 (it actually is staded on wowdev.wiki but I skimmed through article and didn't realise until later).

Glad to hear you figured it out, I couldn't make heads or tails of that file myself. If you can update that ID, I'll give it a few more tests, but from what I saw it looks good to be merged.

**Comment by Alyst3r** [comment]
One thing I did not figure out so far is why some values are in the negative but hey, as long as it works, it works ;].

**Comment by heyitsbench** [comment]
And the [new diff](https://github.com/heyitsbench/pubrepo/compare/25538cf..743bd04). From what I tested it looks to be quite a bit better. Thank you very much again for the PR! ❤️

**Pull request merged**
